RamonUnch/AltSnap

hooks.c

Force check hotkeys state when performing mouse wheel actions.
Fixes RamonUnch/AltDrag#74

Force check hotkeys state

---

altsnap.c
altsnap.rc
hooks.c

Better handling of borderless option

---

hooks.c

Fixes slide through bug on sizeable windows with

---

hooks.c

minor fixes and close corner resize mode

---

README.md
README_ko-KR.md
README_zh-CN.md

Fixed many incorrect statements.
Raised compatibility to Windows 11 in the Readme file.

Readme Update

---

hooks.c

Adjust Long click move

---

hooks.c

Make shift behave

---

altsnap.c
hooks.c
hooks.h

* More tuneup to the enum code
* fixes: #213

Show checkmark on the Action menu

---

hooks.c
zones.c

Quick fix of #220

---

hooks.c

Add opacity to hollow rectangle (FullWin=0)

---

zones.c

Take AeroMaxSpeed into account for Zones

---

hooks.c

Generalize caption button handling

---

hooks.c

Try to fix focusing problems

---

altsnap.c
config.c
hooks.c

Also make source compatible with Open Watcom compiler

Fixes Lower when performed from Action Menu

---

altsnap.c
hooks.c

Fixes #240
Also Fixes Side snapping from Action menu
Also Adds Roll/Unroll Window check state.

Allow to customize the Action Menu

---

hooks.c

Allow non primary GrabWithAlt

---

hooks.c

Fixes: #255 
Also fix Action Menu code

Fix the DragSendsAltCtrl option

---

hooks.c
hooks.h
zones.c

Allow to step/extend to the left top right or bottom to zones

---

hooks.c

Fix LongClickMove

---

hooks.c

 Left click to close window in a window list

---

tray.c

Fix tray icon disaplay in suspend state

---

altsnap.c
config.c
hooks.c

Minor fixes

---

hooks.c

Add a MaxKeysNum option

---

languages.c
nanolibc.h

Avpid calling GetPrivateProfileString() in a loop. Reduces by half the number of disk reads at startup.

Translation loading optimisation

---

altsnap.c
config.c
hooks.c
hooks.h
languages.c
languages.h
nanolibc.h
unfuck.h
zones.c

Also Always block Hotclick UP
* wip: #334

Minimize disk readings when starting AltSnap

---

config.c
tray.c

Add theme support

---

hooks.c

new blacklist formats:
`exename.exe:title|class`
`title|class` == `*:title|class`
`exename.exe`
`exename.exe:title` == `exename.exe:title|*`

Unify window and process blacklist

---

hooks.c

Add specific blacklist for Inactive scroll option

---

hooks.c

* Fixes: #355
Also use BT_PROBE modifier for balcklist probing for future improvemens

Fix button up being improperly blocked sometime

---

altsnap.c
altsnap.nsi
altsnap.rc
hooks.c
hooks.h
hooks.rc
languages.h
tray.c
unfuck.h
zones.c

Multiple Snap Layout Support

---

config.c
hooks.c
hooks.h
languages.h

Add extend to next edge option

---

config.c
hooks.c
hooks.h
languages.h

Extend To next edge for Keyboard

---

hooks.c

NPStacked fix

---

altsnap.c
config.c

Fix dialog crash

---

hooks.c

Make esc configurable

---

config.c
unfuck.h

EnableDlgItem() not to disable focused windows

---

config.c
languages.h

Also add the Clikc display to the test window

Config refactoring

---

snap.c

Scale FancyZones restore size

---

hooks.c

Ensure clicks are forwarded correctly

---

hooks.c
unfuck.h

Add IgnoreMinMaxInfo advanced option

---

altsnap.c
config.c
hooks.c
hooks.h
languages.h
tray.c
zones.c

Add the Edit snap layout tray menu entry

---

hooks.c

Allow xxbutton as hotclick

---

hooks.c

1. Do not Move/resize a window if the position did not change at all. Progress on #448 
2. Do not resize Windows that are not resizable in SnapToCorner() function. #447

minor-fixes

---

hooks.c

Improve RezTimer options

---

config.c
hooks.c
hooks.h
languages.h

Add the focus left/top/right/bottom window options

---

hooks.c

Add the option to change the LongClick move delay

---

hooks.c

Fix more invisible borders problems

---

hooks.c

Transform Snap to corner in move to next edge for non-resizable windows

---

hooks.c
unfuck.h

Improve FocusLTRB ation

---

altsnap.nsi
languages.h
sch_Off.bat
sch_On.bat

Well, basically the option is `schtasks.exe /CREATE /XML .\AltSnap.xml /TR "%~dp0AltSnap.exe"`
The task can be created without the xml file but it will get terminated after 3 days and there are no ways to change that unless yu use an xml file.
* Fixes #475.

Add batch files to setup Scheduled task

---

altsnap.c
tray.c

* Progress on: #479 
* Help dialog updated!
You can use `AltSnap.exe -l3` to select layout number 3.

Add the -l cmdline option to select layout

---

altsnap.c

Add the -r option to relaod the config

---

hooks.c

Also disable Wheel action when Disabling movment

---

hooks.c
hooks.h
nanolibc.h

* Fixes: #205
* Fixes: #422
* Fixes: #493

Add Shortcut Sending option

---

hooks.c
hooks.h

Fix Volume action and WIP on Brightness

---

hooks.c

Titlebar action must have precedence over Hotclick

---

hooks.c
zones.c

Add Snap Layout Preview

---

hooks.c
unfuck.h

Ignore Ctrl if simulated (via AltGr for example)

---

zones.c

Improve Move to left/top/right/bottom zone

---

AltSnap.exe.manifest

Add the uiAccess flag in the .manifest file so that t can be easily turned on with the ahk script
related: #538

Update .manifest file

---

hooks.c

Only call the NotifyWinEvent After drag actually started.
* Fixes #575

NotifyWinEvent only After Drag started

---

languages.h

use a macro for centralized lang handling

reafactor language struct definition

---

altsnap.c
config.c
hooks.c
languages.c
languages.h
tray.c

A new section can be created in the translation file `[ToolTips]` the same verbs are used

Add ToolTips to the config dialog

---

hooks.c
hooks.h
unfuck.h

MouseMove(pt) should always be in the worker thread.

Make Use of a worker thread

---

altsnap.nsi

Fix NSI installer with new translations

---

hooks.c

Different actions for Wheel Up and Down
